-- AlterTable
ALTER TABLE "CombustivelData" ALTER COLUMN "kgCO2" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "kgCH4" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "kgN2O" SET DATA TYPE DOUBLE PRECISION;
